<?
$PERM["catalog"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["search"]["5"]="W";
$PERM["projects"]["5"]="W";
$PERM["price"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["include"]["5"]="W";
$PERM["contacts"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
$PERM["/"]["*"]="R";
?>