<?
require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/header.php");
$APPLICATION->SetTitle("Каталог продукции");
?><? $APPLICATION->IncludeComponent(
    "bitrix:catalog",
    "catalog",
    array(
        "ACTION_VARIABLE" => "action",
        "ADD_ELEMENT_CHAIN" => "N",
        "ADD_PROPERTIES_TO_BASKET" => "Y",
        "ADD_SECTIONS_CHAIN" => "Y",
        "AJAX_MODE" => "N",
        "AJAX_OPTION_ADDITIONAL" => "",
        "AJAX_OPTION_HISTORY" => "N",
        "AJAX_OPTION_JUMP" => "N",
        "AJAX_OPTION_STYLE" => "Y",
        "BASKET_URL" => "",
        "CACHE_FILTER" => "N",
        "CACHE_GROUPS" => "Y",
        "CACHE_TIME" => "36000000",
        "CACHE_TYPE" => "A",
        "COMPATIBLE_MODE" => "Y",
        "COMPOSITE_FRAME_MODE" => "A",
        "COMPOSITE_FRAME_TYPE" => "AUTO",
        "DETAIL_BACKGROUND_IMAGE" => "-",
        "DETAIL_BROWSER_TITLE" => "-",
        "DETAIL_CHECK_SECTION_ID_VARIABLE" => "N",
        "DETAIL_META_DESCRIPTION" => "-",
        "DETAIL_META_KEYWORDS" => "-",
        "DETAIL_PROPERTY_CODE" => array("FORM_ORDER", "FORM_QUESTION", "PRICE", "OLD_PRICE", "CURRENCY", "HIT", "STATUS", "ART_NUMBER", "LINK_GOODS", "MARKA", "CVET", "MATERIAL_OTDELKI", "KARKAS_KRESLA", "MATERIAL_KRESTOVINY", "PRINCIP_RABOTY_KOTLA", "UPRAVLENIE", "EHNERGOZAVISIMYJ", "RAZMESHCHENIE", "TIP_TOPLIVA", "SROK_LICENZII", "KOLICHESTVO_USTROJSTV", "RAZRYADNOST_SISTEMY", "GABARITY", "VES", "PROIZVODITEL", "VOZRASTNOE_OGRANICHENIE", "PLATFORMA", "GARANTIYA", "GABARITNYE_RAZMERY", "MATERIAL", "SKOROST_FILTRACI", "RESURS", "TABLE_ARTICUL", "TABLE_DLINA", "TABLE_UPAKOVKA", "TABLE_PRICE", ""),
        "DETAIL_SET_CANONICAL_URL" => "Y",
        "DETAIL_SHOW_PICTURE" => "Y",
        "DETAIL_STRICT_SECTION_CHECK" => "N",
        "DISABLE_INIT_JS_IN_COMPONENT" => "N",
        "DISPLAY_BOTTOM_PAGER" => "Y",
        "DISPLAY_TOP_PAGER" => "N",
        "ELEMENT_SORT_FIELD" => "sort",
        "ELEMENT_SORT_FIELD2" => "id",
        "ELEMENT_SORT_ORDER" => "asc",
        "ELEMENT_SORT_ORDER2" => "desc",
        "FILE_404" => "",
        "IBLOCK_ID" => "15",
        "IBLOCK_TYPE" => "marsd_bitcorp_s1",
        "INCLUDE_SUBSECTIONS" => "Y",
        "LINE_ELEMENT_COUNT" => "3",
        "LINK_ELEMENTS_URL" => "link.php?PARENT_ELEMENT_ID=#ELEMENT_ID#",
        "LINK_IBLOCK_ID" => "",
        "LINK_IBLOCK_TYPE" => "",
        "LINK_PROPERTY_SID" => "",
        "LIST_BROWSER_TITLE" => "-",
        "LIST_META_DESCRIPTION" => "-",
        "LIST_META_KEYWORDS" => "-",
        "LIST_PROPERTY_CODE" => array("FORM_ORDER", "FORM_QUESTION", "PRICE", "OLD_PRICE", "CURRENCY", "HIT", "STATUS", "MARKA", ""),
        "MESSAGE_404" => "",
        "MESS_BTN_ADD_TO_BASKET" => "В корзину",
        "MESS_BTN_BUY" => "Купить",
        "MESS_BTN_COMPARE" => "Сравнение",
        "MESS_BTN_DETAIL" => "Подробнее",
        "MESS_BTN_ORDER" => "Оставить заявку",
        "MESS_BTN_QUESTION" => "Задать вопрос",
        "MESS_NOT_AVAILABLE" => "Нет в наличии",
        "MESS_OTHER_ITEMS" => "Похожие товары",
        "MESS_TAB_DESCRIPTION" => "Описание",
        "MESS_TAB_FILES" => "Файлы",
        "MESS_TAB_PROPS" => "Характеристики",
        "PAGER_BASE_LINK_ENABLE" => "N",
        "PAGER_DESC_NUMBERING" => "N",
        "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
        "PAGER_SHOW_ALL" => "N",
        "PAGER_SHOW_ALWAYS" => "N",
        "PAGER_TEMPLATE" => "modern",
        "PAGER_TITLE" => "Товары",
        "PAGE_ELEMENT_COUNT" => "9",
        "PARTIAL_PRODUCT_PROPERTIES" => "N",
        "PRICE_CODE" => array(),
        "PRICE_VAT_INCLUDE" => "Y",
        "PRICE_VAT_SHOW_VALUE" => "N",
        "PRODUCT_ID_VARIABLE" => "id",
        "PRODUCT_PROPERTIES" => "",
        "PRODUCT_PROPS_VARIABLE" => "prop",
        "PRODUCT_QUANTITY_VARIABLE" => "",
        "SECTION_BACKGROUND_IMAGE" => "-",
        "SECTION_COUNT_ELEMENTS" => "N",
        "SECTION_FIELDS" => array("NAME", "PICTURE", "DETAIL_PICTURE", ""),
        "SECTION_ID_VARIABLE" => "SECTION_ID",
        "SECTION_SHOW_DESCR" => "N",
        "SECTION_SHOW_PARENT_NAME" => "N",
        "SECTION_SHOW_PREVIEW_TEXT" => "Y",
        "SECTION_SHOW_PREVIEW_TEXT_POSITION" => "top",
        "SECTION_TOP_DEPTH" => "2",
        "SECTION_USER_FIELDS" => array("UF_SECTION_DESCR", ""),
        "SEF_FOLDER" => "/catalog/",
        "SEF_MODE" => "Y",
        "SEF_URL_TEMPLATES" => array("compare" => "compare.php?action=#ACTION_CODE#", "element" => "#SECTION_CODE_PATH#/#ELEMENT_CODE#/", "section" => "#SECTION_CODE_PATH#/", "sections" => "", "smart_filter" => "#SECTION_ID#/filter/#SMART_FILTER_PATH#/apply/"),
        "SET_LAST_MODIFIED" => "N",
        "SET_STATUS_404" => "Y",
        "SET_TITLE" => "Y",
        "SHOW_404" => "Y",
        "SHOW_DEACTIVATED" => "N",
        "SHOW_PRICE_COUNT" => "1",
        "SHOW_TOP_ELEMENTS" => "N",
        "TOP_ELEMENT_COUNT" => "9",
        "TOP_ELEMENT_SORT_FIELD" => "sort",
        "TOP_ELEMENT_SORT_FIELD2" => "id",
        "TOP_ELEMENT_SORT_ORDER" => "asc",
        "TOP_ELEMENT_SORT_ORDER2" => "desc",
        "TOP_LINE_ELEMENT_COUNT" => "3",
        "TOP_PROPERTY_CODE" => array(0 => "", 1 => "",),
        "USER_CONSENT" => "N",
        "USER_CONSENT_ID" => "0",
        "USER_CONSENT_IS_CHECKED" => "Y",
        "USER_CONSENT_IS_LOADED" => "N",
        "USE_COMPARE" => "N",
        "USE_ELEMENT_COUNTER" => "N",
        "USE_FILTER" => "N",
        "USE_MAIN_ELEMENT_SECTION" => "Y",
        "USE_PRICE_COUNT" => "N",
        "USE_PRODUCT_QUANTITY" => "N",
        "USE_STORE" => "N",
        "VARIABLE_ALIASES" => array("compare" => array("ACTION_CODE" => "action",),)
    )
); ?><? require($_SERVER["DOCUMENT_ROOT"] . "/bitrix/footer.php"); ?>